### ISSUE TITLE
same condition

### ISSUE THREAD

**Issue by parthivppatel** [Puzer-03/portfolio#19]
in **login_filter.java**'

line no 65 to 77 there are same code in if and else condition
and I guess this conditions are not use(because in this condition print statement are not execute) 
so @Puzer-03  and @hetparekh21  need of this

**Comment by hetparekh21** [comment]
line 65 to 77 
`

                                        System.out.println(user_id);
					
					user u = data.get_person(Integer.parseInt(user_id));
					
					sc.setAttribute("user", u);
					System.out.println("User id is "+u.user_id);
					sc.setAttribute("user_id", u.user_id);
					sc.setAttribute("username",	 u.name);
					System.out.println("username is ");
					
					user_cookie_found = true ;
					
					// pass the request along the filter chain i.e index.jsp
					System.out.println("end");

`

is this what you are talking about ? @parthivppatel 
if not pls provide the code.

**Comment by parthivppatel** [comment]
no I am talking about this

`if(!user_cookie_found) {
				
				System.out.println("redirect to login 1");
				req.getRequestDispatcher("login.jsp").forward(req, response);
				
			}
			
		}else {
			
			System.out.println("redirect to login 2");
			req.getRequestDispatcher("login.jsp").forward(req, response);
			
		}`

**Comment by hetparekh21** [comment]
yes these are important 

this one moves to login page if the cookies are not found at all
`
                if(!user_cookie_found) {

			System.out.println("redirect to login 1");
			req.getRequestDispatcher("login.jsp").forward(req, response);
			
		}

`
and this one is if the specific cookie is not found i.e user_id
`       
        else {
		
		System.out.println("redirect to login 2");
		req.getRequestDispatcher("login.jsp").forward(req, response);
		
	}

`
