### ISSUE TITLE
Database 

### ISSUE THREAD

**Issue by hetparekh21** [Puzer-03/portfolio#2]
Add some dummy data in the portfolio_db.mysql  (for all tables) for future testing

**Comment by Puzer-03** [comment]
Added dummy data into tables

**Comment by hetparekh21** [comment]
Data not enough , Add more users (at least  5-10)

**Comment by Puzer-03** [comment]
Added 4 more data into user, contact_info and about table

**Comment by Puzer-03** [comment]
Now we cannot add any more user as the database accept password in ecncrypted form
