### ISSUE TITLE
refresh sign in and sign up issue

### ISSUE THREAD

**Issue by parthivppatel** [Puzer-03/portfolio#20]
when I first sign in and write wrong password I got warning of this but
1)when I click on sign up the warning message is not disappearing
2)on refresh click of login.jsp  thw warning message is not diappearing

same this is doing when I click on create account and enter same existing email id show I got the warning message and I redirect on sign in page but the warning message is not disappearing and refresh on index.jsp warning message is not disappering

**Comment by hetparekh21** [comment]
for this we might have to leave login.java and do the validation on the login.jsp page itself

**Comment by hetparekh21** [comment]
we'll solve this tomorrow

**Comment by parthivppatel** [comment]
in sign in and sign up pages instead of  use include method we use server side validation
please suggest I guess this looks better

**Comment by hetparekh21** [comment]
Solved

**Comment by parthivppatel** [comment]
@hetparekh21  what is the changes after pull users are not login and not sign up because of admin/admin url(2 times)
![Screenshot (299)](https://user-images.githubusercontent.com/106151693/192859646-d96c9a84-cff1-4d84-9e39-4a6f1efcf372.png)

**Comment by Puzer-03** [comment]
issue solved af
