### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by parthivppatel** [Puzer-03/portfolio#21]
in **contact_info.jsp** :

when I add the user's information for first time it was added in database when I want to update it gives me exception of java 
so check it(and when I back from it and refresh the page the updated data is showed )

@hetparekh21  or @Puzer-03  who know JSTL solve it

**Comment by parthivppatel** [comment]
issue solved there is simple condition problem

**Comment by Puzer-03** [comment]
issue resolved there was a small error in jstl tag
