### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by hetparekh21** [Puzer-03/portfolio#25]
Map messages in the admin panel (messages)

**Comment by parthivppatel** [comment]
in the first portfolio when I submit data, it throws error of encoding or decoding ,but data is store to database and map into messages so @Puzer-03  please review what is this issue , I also try to solve this

**Comment by parthivppatel** [comment]
done mapping in messages 
@Puzer-03 i added a new page preview.jsp in webapp ,you can add your cards in this page , I only put the links of portfolio in this page not the designing so please first pull than write your code

**Comment by parthivppatel** [comment]
#25  is done
