### ISSUE TITLE
New Page

### ISSUE THREAD

**Issue by hetparekh21** [Puzer-03/portfolio#26]
Template page in the admin panel (create portfolio section)

**Comment by Puzer-03** [comment]
![Capture](https://user-images.githubusercontent.com/62717231/193445063-6d1df353-1a97-4cea-b0b2-88d094c24ed7.PNG)

will this type of card work?

**Comment by hetparekh21** [comment]
👍🏻

**Comment by Puzer-03** [comment]
new page added and linked with portfolio link. pictures of template are left to be added
