### ISSUE TITLE
Handling errors on all page

### ISSUE THREAD

**Issue by Puzer-03** [Puzer-03/portfolio#29]
We need to handle error for all pages. My suggestion is we can use context to save error and show on the corresponding page

**Comment by hetparekh21** [comment]
migrating resetpassword.java to jsp .

**Comment by hetparekh21** [comment]
Are we setting up an otp system ? 
if yes than close this issue

**Comment by Puzer-03** [comment]
why?

**Comment by hetparekh21** [comment]
issue solved
