### ISSUE TITLE
conflicts problem

### ISSUE THREAD

**Issue by parthivppatel** [Puzer-03/portfolio#4]
when I pull the latest code I have conflicts in that , i try to resolve it but conflicts are solved yet , so please tell what to do

**Comment by hetparekh21** [comment]
@parthivppatel 
Try adding the external jars (situated in: 
src/main/webapp/web-inf/lib)
In the build config

**Comment by parthivppatel** [comment]
@hetparekh21 I build it but conflicts are because of git repo
