### ISSUE TITLE
password (remaining)

### ISSUE THREAD

**Issue by parthivppatel** [Puzer-03/portfolio#5]
save password in encrypted form in database

**Comment by Puzer-03** [comment]
issue closed

**Comment by hetparekh21** [comment]
bro the password is encrypted but in the Edit profile it is shown in the encrypted form only . That's not right .

**Comment by Puzer-03** [comment]
but we cannot show the password in that form and also we are saving it in md5 format so will be unable to decrypt it

**Comment by hetparekh21** [comment]
then instead of giving an input field we should give a different page or pop-up to change password

**Comment by Puzer-03** [comment]
i didn't get your poinr

**Comment by hetparekh21** [comment]
> give a button or something to change the password 

take password as input --> (verify) --> new pass , confirm pass 

> That way we won't have to show the encrypted form .

**Comment by parthivppatel** [comment]
@hetparekh21  you are wright  path is like
security questions(submit)> new page(password and confirm password column)  on submit>redirect on login.jsp again

**Comment by hetparekh21** [comment]
I am not talking about security questions . 
I am telling you to give a "change pass" button instead that password field
![Screenshot (31)](https://user-images.githubusercontent.com/70949142/192160524-7381845e-7df0-4161-9c42-fbdee755a637.png)

**Comment by Puzer-03** [comment]
what if we keep the password field value empty instead of showing a popup

**Comment by hetparekh21** [comment]
No , def not an empty field

**Comment by Puzer-03** [comment]
![image](https://user-images.githubusercontent.com/62717231/193445314-eec7c165-fc55-4ae1-b492-80ee52a760ca.png)

i am talking about this

**Comment by hetparekh21** [comment]
Noooo

**Comment by Puzer-03** [comment]
okayy

**Comment by Puzer-03** [comment]
popup added issue solved
